version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: umbral_backend
    restart: always
    # Conexión a la máquina host (Ubuntu)
    extra_hosts:
       - "host.docker.internal:host-gateway"
    environment:
      # CAMBIO: Ahora apunta a host.docker.internal para conectar con tu Postgres local
      DATABASE_URL: postgresql://umbral_user:umbral_password_2024@host.docker.internal:5432/umbral_db
      JWT_SECRET: umbral-jwt-secret-cambiar-en-produccion-2024
      JWT_EXPIRES_IN: 8h
      MFA_APP_NAME: Umbral SpA
      FRONTEND_URL: http://192.168.1.183:5173
    ports:
      - "3001:3001"
    # CAMBIO: Se añaden volúmenes para persistir el build y las dependencias dentro del contenedor
    volumes:
      - ./backend:/app
      - /app/node_modules
      - /app/dist

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: umbral_frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "5173:5173"
    # CAMBIO: Se añaden volúmenes para evitar que tu carpeta local pise las dependencias de Docker
    volumes:
      - ./frontend:/app
      - /app/node_modules
      