services:
  - type: web
    name: control-fichas-backend
    env: node

    rootDir: backend

    buildCommand: npm ci && npm run build

    preDeployCommand: npm run prisma:migrate:deploy && npm run seed
    
    startCommand: npm run start:prod