services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile

    volumes:
      - ..:/workspace:cached
      - backend_node_modules:/workspace/backend/node_modules
      - frontend_node_modules:/workspace/frontend/node_modules
    
    command: sleep infinity

    env_file:
      - .env.devcontainer
    
    depends_on:
      - postgres

  postgres:
    image: postgres:16

    restart: unless-stopped

    env_file:
      - .env.devcontainer

    volumes:
      - postgres_data:/var/lib/postgresql/data
    
  pgadmin:
    image: dpage/pgadmin4

    restart: unless-stopped
    
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@local.dev
      PGADMIN_DEFAULT_PASSWORD: admin123
    
    ports:
      - "8080:80"

    depends_on:
      - postgres

    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data:
  backend_node_modules:
  frontend_node_modules:
  pgadmin_data: